all:
  hosts:
    master-1:
      ansible_host: 51.250.7.66
      ip: 10.0.1.34
      access_ip: 10.0.1.34
      ansible_user: debian
    worker-1:
      ansible_host: 84.201.159.138
      ip: 10.0.1.19
      access_ip: 10.0.1.19
      ansible_user: debian
    worker-2:
      ansible_host: 89.169.142.229
      ip: 10.0.1.10
      access_ip: 10.0.1.10
      ansible_user: debian
  children:
    kube_control_plane:
      hosts:
        master-1:
    kube_node:
      hosts:
        worker-1:
        worker-2:
    etcd:
      hosts:
        master-1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}