---
- name: Установка pip
  hosts: master-1
  become: true

  tasks:

    - name: Скачиваем файл get-pip.py
      ansible.builtin.get_url:
        url: https://bootstrap.pypa.io/get-pip.py
        dest: "./"

    - name: Удаляем EXTERNALLY-MANAGED
      ansible.builtin.file:
        path: /usr/lib/python3.11/EXTERNALLY-MANAGED
        state: absent

    - name: Устанавливаем pip
      ansible.builtin.shell: python3.11 get-pip.py



- name: Установка зависимостей из ansible-playbook kubespray
  hosts: master-1
  become: true

  tasks:

    - name: Выполнение apt update и установка git
      ansible.builtin.apt:
        update_cache: true
        pkg:
        - git

    - name: Клонируем kubespray из репозитория
      ansible.builtin.git:
        repo: https://github.com/kubernetes-sigs/kubespray.git
        dest: ./kubespray

    - name: Изменение прав на папку kubspray
      ansible.builtin.file:
        dest: ./kubespray
        recurse: yes
        owner: debian
        group: debian

    - name: Установка зависимостей из requirements.txt
      ansible.builtin.pip:
        requirements: /home/debian/kubespray/requirements.txt
        extra_args: -r /home/debian/kubespray/requirements.txt

    - name: Копирование содержимого папки inventory/sample в папку inventory/mycluster
      ansible.builtin.copy:
        src: /home/debian/kubespray/inventory/sample/
        dest: /home/debian/kubespray/inventory/mycluster/
        remote_src: true


- name: Подготовка master-node к установке kubespray из ansible-playbook
  hosts: master-1
  become: true

  tasks:

    - name: Копирование на master-node файла hosts.yml
      ansible.builtin.copy:
        src: ./inventory/hosts.yml
        dest: ./kubespray/inventory/mycluster/

    - name: Копирование на мастер приватного ключа
      ansible.builtin.copy:
        src: /home/slava/.ssh/id_rsa
        dest: ./.ssh
        owner: debian
        mode: '0600'